services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
      - "5000:5000"
    restart: always

  bdd:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

