services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend_backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - frontend_backend
      - backend_db

  bdd:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_db

volumes:
  mongo-data:

networks:
  frontend_backend:
    driver: bridge
  backend_db:
    driver: bridge

